### ISSUE TITLE
[Error of loading data] UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte

### ISSUE THREAD

**Issue by ghost** [fanhqme/DeepPointSet#20]
Python: 3.6
Ubuntu: 18.04
Tensorflow: 1.13.1

There is an error when loading the '.gz' files:
`Traceback (most recent call last):
  File "/home/tifo-kj/anaconda3/envs/learn/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/tifo-kj/Documents/PointSetGeneration/depthestimate/BatchFetcher.py", line 71, in run
    self.queue.put(self.work(self.bno%300000))
  File "/home/tifo-kj/Documents/PointSetGeneration/depthestimate/BatchFetcher.py", line 39, in work
    binfile=zlib.decompress(open(path,'r').read())
  File "/home/tifo-kj/anaconda3/envs/learn/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte
`

I tried some suggestions online, but failed. Could you please help? Thank you very mush!

**Comment by ghost** [comment]
Turns out I have to use python 2.7. I tried to change the code to apply python 3.6, but failed.

**Comment by garimss** [comment]
@kayee6
v,p =pickle.load(fin, encoding='iso-8859-1') I used this instead utf-8. and it works for me

**Comment by abhishekk06** [comment]
Hi 

Any idea how to solve this in python3.6. Can't go back to python2.7 because of other package constraints (like cv2)
