### ISSUE TITLE
when I run runr2n2_128.py I get assertion error Why?

### ISSUE THREAD

**Issue by garimss** [fanhqme/DeepPointSet#25]
(fastai-3.7) D:\git_hub\3D\PointSetGeneration\demo>python r2n2_128.py leg.png r2n2_128_v1.pkl
C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\h5py\__init__.py:72: UserWarning: h5py is running against HDF5 1.10.2 when it was built against 1.10.3, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
curses is not supported on this machine (please install/reinstall curses for an optimal experience)
WARNING:tensorflow:From C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\tflearn\initializations.py:119: UniformUnitScaling.__init__ (from tensorflow.python.ops.init_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
2019-09-11 18:01:23.634506: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-09-11 18:01:23.828876: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1070 with Max-Q Design major: 6 minor: 1 memoryClockRate(GHz): 1.379
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.63GiB
2019-09-11 18:01:23.839396: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-09-11 18:01:24.375509: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-09-11 18:01:24.379886: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-09-11 18:01:24.382626: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-09-11 18:01:24.386412: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6380 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "r2n2_128.py", line 97, in <module>
    ret=run_image(model,img_in)
  File "r2n2_128.py", line 86, in run_image
    assert(img_in.shape==(HEIGHT,WIDTH,4))
AssertionError

**Comment by Jack-Crum** [comment]
May I ask, would you like to share your PLK file (twobranch_v1.pkl) with me? I have no idea to fetch it but ask you, it will help me a lot, thank you!!!
my email address is **JiehuiHuang1107@163.com**
